apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/recipesage-selfhost-default: "true"
        io.kompose.service: api
    spec:
      containers:
        - args:
            - npx
            - ts-node
            - --swc
            - --project
            - packages/backend/tsconfig.json
            - packages/backend/src/bin/www
          env:
            - name: BROWSERLESS_HOST
              value: browserless
            - name: BROWSERLESS_PORT
              value: "3000"
            - name: DATABASE_URL
              value: postgresql://recipesage_selfhost:recipesage_selfhost@postgres:5432/recipesage_selfhost
            - name: FILESYSTEM_STORAGE_PATH
              value: /rs-media
            - name: GRIP_KEY
              value: changeme
            - name: GRIP_URL
              value: http://pushpin:5561/
            - name: INGREDIENT_INSTRUCTION_CLASSIFIER_URL
              value: http://ingredient-instruction-classifier:3000/
            - name: NODE_ENV
              value: selfhost
            - name: POSTGRES_DB
              value: recipesage_selfhost
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_LOGGING
              value: "false"
            - name: POSTGRES_PASSWORD
              value: recipesage_selfhost
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_SSL
              value: "false"
            - name: POSTGRES_USER
              value: recipesage_selfhost
            - name: SEARCH_PROVIDER
              value: typesense
            - name: STORAGE_TYPE
              value: filesystem
            - name: TYPESENSE_API_KEY
              value: recipesage_selfhost
            - name: TYPESENSE_NODES
              value: '[{"host": "typesense", "port": 8108, "protocol": "http"}]'
            - name: VERBOSE
              value: "false"
            - name: VERSION
              value: selfhost
          image: julianpoy/recipesage-selfhost:api-v2.12.10
          name: recipesage-api
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /rs-media
              name: apimedia
      restartPolicy: Always
      volumes:
        - name: apimedia
          persistentVolumeClaim:
            claimName: apimedia
status: {}
