apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: browserless
  name: browserless
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: browserless
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/recipesage-selfhost-default: "true"
        io.kompose.service: browserless
    spec:
      containers:
        - env:
            - name: MAX_CONCURRENT_SESSIONS
              value: "3"
            - name: MAX_QUEUE_LENGTH
              value: "10"
          image: browserless/chrome:1.57-puppeteer-19.2.2
          name: recipesage-browserless
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
