apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: ingredient-instruction-classifier
  name: ingredient-instruction-classifier
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ingredient-instruction-classifier
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/recipesage-selfhost-default: "true"
        io.kompose.service: ingredient-instruction-classifier
    spec:
      containers:
        - env:
            - name: PREDICTION_CONCURRENCY
              value: "4"
            - name: SENTENCE_EMBEDDING_BATCH_SIZE
              value: "200"
          image: julianpoy/ingredient-instruction-classifier:1.4.9
          name: recipesage-classifier
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
