apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: proxy
  name: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: proxy
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/recipesage-selfhost-default: "true"
        io.kompose.service: proxy
    spec:
      containers:
        - image: nginx
          name: recipesage-proxy
          ports:
            - containerPort: 80
              hostPort: 8820
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: proxy.conf
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: proxycfg
status: {}
